name: Linux Cppcheck

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'documentation/**'
      - 'docs/**'
      - 'LICENSE'
      - '.gitignore'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build-cmake:
    uses: ./.github/workflows/cmake_linux.yml

  build-boost:
    uses: ./.github/workflows/boost_linux.yml
    with:
      boost_version: "1.91.0"

  build-openssl:
    uses: ./.github/workflows/openssl_linux.yml

  build-opencl:
    uses: ./.github/workflows/opencl_linux.yml

  build-cuda:
    uses: ./.github/workflows/cuda_linux.yml

  cppcheck:
    needs: [build-cmake, build-boost, build-openssl, build-opencl, build-cuda]
    runs-on: ubuntu-22.04

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - uses: actions/checkout@v4

      # ===============================
      # Restore and install all deps
      # ===============================
      - name: Setup dependencies
        uses: ./.github/actions/miner/setup-deps
        with:
          cuda: "true"

      # ===============================
      # Install cppcheck
      # ===============================
      - name: Install cppcheck
        run: sudo apt-get install -y cppcheck

      # ===============================
      # Configure Miner ALL (AMD + NVIDIA + CPU)
      # ===============================
      - name: Configure CMake
        env:
          CUDA_HOME: /usr/local/cuda-13.1
          CUDACXX: /usr/local/cuda-13.1/bin/nvcc
          LD_LIBRARY_PATH: /usr/local/cuda-13.1/lib64:/usr/local/lib
        run: |
          mkdir build
          cd build
          cmake .. \
            -DCMAKE_BUILD_TYPE=Release \
            -DNVCC_ARCH_COMPUTE=89 \
            -DCMAKE_C_COMPILER=clang-15 \
            -DCMAKE_CXX_COMPILER=clang++-15 \
            -DBUILD_EXE_BENCHMARK=OFF \
            -DBUILD_EXE_UNIT_TEST=OFF \
            -DBUILD_EXE_MINER=ON \
            -DBUILD_NVIDIA=ON \
            -DBUILD_AMD=ON \
            -DBUILD_CPU=ON \
            -DENABLE_LTO=OFF \
            -DENABLE_NATIVE=OFF

      # ===============================
      # Run cppcheck via cmake target
      # ===============================
      - name: Run cppcheck
        run: cmake --build build --target cppcheck
